# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshm < Formula
  desc "A pretty, AI-friendly SSH connection manager"
  homepage "https://github.com/michael-ltm/sshm"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.5.1/sshm_darwin_amd64.tar.gz"
      sha256 "c7e31458e8c01a7183e52f0eb67a89c111bde6ac640568c8d3b5945f1c4180c4"

      define_method(:install) do
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.5.1/sshm_darwin_arm64.tar.gz"
      sha256 "528c7756b339c8e6c602998244fea8c461def3f19fee8e2f97825d863ab33f8c"

      define_method(:install) do
        bin.install "sshm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.5.1/sshm_linux_amd64.tar.gz"
      sha256 "1e6cb50614fc94f3124d73b96ba45fc059221780e49ebb9ecfc7dcacffd18076"
      define_method(:install) do
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.5.1/sshm_linux_arm64.tar.gz"
      sha256 "12a4cc37b18e85a0b45b378fa44f542ae9d82e9e377a93104b941c1467513724"
      define_method(:install) do
        bin.install "sshm"
      end
    end
  end

  test do
    system "#{bin}/sshm", "version"
  end
end
