# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshm < Formula
  desc "A pretty, AI-friendly SSH connection manager"
  homepage "https://github.com/michael-ltm/sshm"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.4.1/sshm_darwin_amd64.tar.gz"
      sha256 "4df813914b69eef35d33f65706dacb76a15f21ef4766c573820e88e242cecd14"

      define_method(:install) do
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.4.1/sshm_darwin_arm64.tar.gz"
      sha256 "71762f05c46d4a77d00674128f010d6aca573cff23753670cc86b7b7045efe9f"

      define_method(:install) do
        bin.install "sshm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.4.1/sshm_linux_amd64.tar.gz"
      sha256 "117de44c636c88ed26f73421cc2c66bd692e949969458c17b8fa26f5afdc2f92"
      define_method(:install) do
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.4.1/sshm_linux_arm64.tar.gz"
      sha256 "82dc2fe0c0a047a93f64b25ffff33ba9934f89e4f206a2d9fc0daeeb9de02610"
      define_method(:install) do
        bin.install "sshm"
      end
    end
  end

  test do
    system "#{bin}/sshm", "version"
  end
end
