# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshm < Formula
  desc "A pretty, AI-friendly SSH connection manager"
  homepage "https://github.com/michael-ltm/sshm"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.1.0/sshm_darwin_amd64.tar.gz"
      sha256 "1d1c45c90d0afd95c3fc79f3470c1c12d28731053948b10c7e4e75b75f0fa974"

      define_method(:install) do
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.1.0/sshm_darwin_arm64.tar.gz"
      sha256 "589e3191220ac55173e7ba8269d3f35cf5cec73ab1c23db2b41c42dd872aabe1"

      define_method(:install) do
        bin.install "sshm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.1.0/sshm_linux_amd64.tar.gz"
      sha256 "e21d3ced593e359541c8a4fc64ba678b23394b6c4002d2dc0daeb2f00037d82b"
      define_method(:install) do
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-ltm/sshm/releases/download/v0.1.0/sshm_linux_arm64.tar.gz"
      sha256 "751eb160ba8649bfbb5a617d08cefa96e9a3c2d4d8067a64521534cf4e57ebdb"
      define_method(:install) do
        bin.install "sshm"
      end
    end
  end

  test do
    system "#{bin}/sshm", "version"
  end
end
